### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Aculoss** [klinbee/Flattened-Dimensions#1]
Could you add a version of "Flat Dimensions with Caves" with the bedrock ceiling in the nether please?

**Comment by klinbee** [comment]
With the ceiling? You mean the nether ceiling?

**Comment by Aculoss** [comment]
> With the ceiling? You mean the nether ceiling?

Yes please

**Comment by Quidvio** [comment]
One more question, would you want there to be a layer of like 3 blocks below the bedrock ceiling (like it is a reflection of the floor)

**Comment by Quidvio** [comment]
![image](https://github.com/Quidvio/Flattened-Dimensions/assets/105707614/56cb200d-477b-4f8c-9caa-3b088587b71c)

This is what I have right now. I capped it at 104, so it still looks cave-y (and retains base worldgen, which is the point of the flat dimension versions) and has flat tendencies. Do you think it would be better to just make it solid up top?

**Comment by klinbee** [comment]
> > With the ceiling? You mean the nether ceiling?
> 
> Yes please

![image](https://github.com/Quidvio/Flattened-Dimensions/assets/105707614/352fbef5-9b09-4b4c-88b2-bcd4796a08a1)

This is what I have right now. I capped it at 104, so it still looks cave-y (and retains base worldgen, which is the point of the flat dimension versions) and has flat tendencies. Do you think it would be better to just make it fully solid and flat up top (minus the carver caves, or should I limit those vertically too??)

**Comment by Aculoss** [comment]
I think you should take out the carver caves and just have the bedrock.

**Comment by klinbee** [comment]
> I think you should take out the carver caves and just have the bedrock.

![image](https://github.com/Quidvio/Flattened-Dimensions/assets/105707614/d377c1c7-39af-46c9-a20c-ad8a3a7453fa)
If this is good, I'll add it to a separate branch on here.

**Comment by Aculoss** [comment]
That is great! Is there no way to take out the basalt dripping down?

**Comment by klinbee** [comment]
> That is great! Is there no way to take out the basalt dripping down?

Yeah it's possible to remove, you just didn't specify that you wanted that feature removed.

I'll be able to do that and then publish it tomorrow, I'm headed to bed right now in my time zone.

**Comment by Aculoss** [comment]
> > That is great! Is there no way to take out the basalt dripping down?
> 
> Yeah it's possible to remove, you just didn't specify that you wanted that feature removed.
> 
> I'll be able to do that and then publish it tomorrow, I'm headed to bed right now in my time zone.

You are a legend! Thank you! Love this datapack

**Comment by klinbee** [comment]
> > > That is great! Is there no way to take out the basalt dripping down?
> > 
> > 
> > Yeah it's possible to remove, you just didn't specify that you wanted that feature removed.
> > I'll be able to do that and then publish it tomorrow, I'm headed to bed right now in my time zone.
> 
> You are a legend! Thank you! Love this datapack

Alrighty, done.
https://github.com/Quidvio/Flattened-Dimensions/tree/FD-With-Caves-Roof-Edit
